include: ['_pages']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
destination: docs
assets:
    sources:
        - _assets
    preproxy: [
        {
          src: "global/favicon/favicon.png",
          args: {magick: {resize: "180x"}, proxy_output_id: "180x"}
        },
        {
          src: "global/favicon/favicon.png",
          args: {magick: {define: "icon:auto-resize=64,48,32,16", format: "ico"}, proxy_output_id: "64x"}
        }
    ]
    raw_precompile: [
        {
          src: "service_worker.js",
          dst: "/service_worker.js"
        },
        {
          src: "robots.txt",
          dst: "/robots.txt"
        },
        {
          src: "img/global/favicon/favicon-64x.ico",
          dst: "/favicon.ico"
        },
        {
          src: "img/global/favicon/favicon-180x.png",
          dst: "/apple-touch-icon.png"
        },
        {
          src: "img/global/favicon/favicon-180x.png",
          dst: "/apple-touch-icon-precomposed.png"
        }
    ]
